kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-test
spec:
  # A deployment's specification really only 
  # has a few useful options
  
  # 1. How many copies of each pod do we want?
  replicas: 1

  # 2. How do want to update the pods?
  # strategy: Recreate

  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      deploy: test
  
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        deploy: test
    spec:
      containers:
        - name: test
          image: ariallas/test
---
apiVersion: v1
kind: Service
metadata:
  name: test-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    deploy: test
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001