apiVersion: v1
kind: Service
metadata:
  name: kate-server-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: kate-server
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: kate-mongo-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: kate-mongo
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30002